### ISSUE TITLE
Refresh page didn't work with route

### ISSUE THREAD

**Issue by kunjee17** [etaque/elm-transit-router#6]
I don't if its just me. And I m totally newbi on this. But if I m on some page link and if I refresh page it didn't work. Normally it should go to that page (route view). 

Let me know if any further details are needed.

**Comment by etaque** [comment]
Yes, it should work if you feed the current path in router init, as here in the example:
https://github.com/etaque/elm-transit-router/blob/master/example/index.html#L30
https://github.com/etaque/elm-transit-router/blob/master/example/src/Main.elm#L12

**Comment by kunjee17** [comment]
@etaque ohk. I ll check it out. Thanks.

**Comment by etaque** [comment]
Come over the Slack channel if you're still stuck:
http://elmlang.herokuapp.com/
